#!/bin/bash

project_template="$1"
meta="$2"
bin_dir=`dirname $0`

echo "bin"

while read -r line; do
    task="$line $meta"
    if [ ! -z "$line" ]; then
        $bin_dir/create-omnifocus-task "$task"
    fi
done < $project_template


