#!/usr/bin/ruby

require 'date'
require 'time'


def get_due_date(string)
  begin
    string = strip_project(string)
    string = strip_context(string)
    puts("parsing date: #{string}")
    date = Date.parse(string)
    date += (date < Date.today) ? 7 : 0
    time = Time.parse(string)
    return "#{date.strftime("%m/%d/%Y")} #{time.strftime("%I:%M %p")}"
  rescue
    return "7:00 PM"
  end
end

def get_project(string)
  project = /\.(\w+)/.match(string).captures[0] rescue "work"
  return project
end

def strip_project(string)
  return string.gsub(/\.\w+/, "")
end

def get_context(string)
  project = /\#(\w+)/.match(string).captures[0] rescue "online"
  return project
end  

def strip_context(string)
  return string.gsub(/\#\w+/, "")
end

def strip_tail(string)
  return string.gsub(/\/\/.*$/, "")
end

def get_task_name(string)
  string = strip_context(string)
  string = strip_project(string)
  string = strip_tail(string)
  return string;
end
      
command = ARGV.join(" ")
project = get_project(command)
context = get_context(command)
task_name = get_task_name(command)
due_date = get_due_date(command)
      

puts "project : #{project}"
puts "context : #{context}"
puts "due date: #{due_date}"
puts "task    : #{task_name}"
puts "HOME: "

puts `osascript #{__dir__}/CreateTask.scpt "#{context}" "#{project}" "#{task_name}" "#{due_date}"`

