#!/usr/bin/env osascript -l JavaScript

function run() {
    try {
        var OmniFocus = Application('OmniFocus');
        var bullet = "❗ ";
        var tasks = OmniFocus.defaultDocument.inbox_tasks.get();
        console.log('got inbox');
        /*
        console.log(`found ${tasks.length} tasks in inbox`);
        tasks.map(function (task, i) {
            console.log(`  ${bullet} ${task.name()}`);
        });
        */

    } catch (e) {
        console.log(`error creating task: ${e}`);
        console.log(e);
    }
}
