#!/bin/bash

########################################################################################################################
# Used by Alfred to populate a list of available options.
# Output formatted as JSON!

log_file="/Users/craser/.todo.log"


template_dir="/Users/craser/bin/project-templates/"
echo "template_dir: ${template_dir}" >> $log_file

cd ${template_dir}

echo '{"items": ['
for template_file in $(ls); do
    echo "template: ${template_file}" >> $log_file
    cat <<EOJ
    {
        "title": "${template_file}",
        "subtitle": "${template_file}",
        "arg": "${template_file}",
        "autocomplete": "${template_file}"
    },
EOJ
done
echo "]}"
echo "done" >> "$log_file"
